configMapGenerator:
- files:
  - application.yml
  name: "82023132-configmap"
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgbaseacr.azurecr.io/82023132
  newTag: "202411250454"
