apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82023132-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: app-82023132.ce-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: app-82023132
            port:
              number: 8080
        pathType: Prefix
